chmod +x dockutil
./dockutil --remove 'Siri'
./dockutil --remove 'Safari'
./dockutil --remove 'Mail'
./dockutil --remove 'Kontakte'
./dockutil --remove 'Kalender'
./dockutil --remove 'Notizen'
./dockutil --remove 'Erinnerungen'
./dockutil --remove 'Karten'
./dockutil --remove 'Fotos'
./dockutil --remove 'Nachrichten'
./dockutil --remove 'FaceTime'
./dockutil --remove 'iTunes'
./dockutil --remove 'iBooks'
./dockutil --add 'Google Chrome' --position 'middle'
./dockutil --add 'Visual Studio Code' --position 'middle'
./dockutil --add 'Sourcetree' --position 'middle'
./dockutil --add 'iTerm' --position 'middle'